import type { Metadata } from "next";
import "../style.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "../Navbar.js";
import Footer from "../Footer.js";

import {DM_Sans, Inter, Roboto} from "next/font/google" 
import AOSInitializer from "../AOSInitializer.jsx"

const headingFont = DM_Sans({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-heading",
});

const paraFont = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-para",
});

const anchorFont = Inter({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-anchor",
});

export const metadata: Metadata = {
  title: "Swipe Fire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${headingFont.variable} ${paraFont.variable} ${anchorFont.variable}`}
      >
        <Navbar/>
        <AOSInitializer />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
